### ISSUE TITLE
List of already presented topics

### ISSUE THREAD

**Issue by Birlinis** [EAL-IT-Technology/ITT2-IT-security#1]
Is there a list of all the topics that have been presented so far because with each week that passes there are more chances to overlap without being aware of? I'm talking about the presentations that the students have to do.

**Comment by moozer** [comment]
We only have [this](https://gitlab.com/ITT-17A/18S_ITS/tree/development/docs/organisation/Article%20Presentation) - peope have not been good at uploading their slides.
